# Generated by Django 4.2.3 on 2023-08-22 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('email_address', models.EmailField(error_messages={'unique': 'El correo electrónico ya se encuentra asociado a un cliente.'}, max_length=254, unique=True)),
                ('phone', models.CharField(error_messages={'unique': 'El número de teléfono ya se encuentra asociado a un cliente.'}, max_length=15, unique=True)),
                ('street_address', models.CharField(max_length=100)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.client'),
        ),
    ]
