# Generated by Django 4.2.3 on 2023-08-26 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_client_order_total_price_orderdetails_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dni',
        ),
    ]
