# Generated by Django 4.2.3 on 2023-09-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_client_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
