# Generated by Django 4.2.3 on 2023-09-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_address',
            new_name='email',
        ),
    ]
