# Generated by Django 4.2.3 on 2023-07-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
