# Generated by Django 4.2.3 on 2023-08-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
