# Generated by Django 4.2.3 on 2023-08-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='user_inventory',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='inventory_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.inventory'),
            preserve_default=False,
        ),
    ]
