# Generated by Django 4.2.3 on 2023-07-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='price',
        ),
    ]
