# Generated by Django 4.2.3 on 2023-07-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='codigo',
            new_name='code',
        ),
    ]
