# Generated by Django 4.2.3 on 2023-10-03 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0003_alter_product_category_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='products',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
